### ISSUE TITLE
Improve GH CI

### ISSUE THREAD

**Issue by francocipollone** [maliput/maliput-rs#16]
## Summary

- [ ] Use this GH Action instead: https://github.com/dtolnay/rust-toolchain
- [ ] Enable fmt check and clippy for better formatting
- [ ] Fix to a particular rustc version.
- Related: https://github.com/maliput/maliput-rs/issues/9

## Suggestion Impl

```yaml
env:
  rust_version: 1.XX.Y

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.rust_version }}
          components: rustfmt, clippy
      - run: cargo fmt -- --check
      - run: cargo clippy
      - run: cargo test
```
